name: Trigger auto deployment for containerapp node2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/node2-AutoDeployTrigger-fcb55a1b-015c-4701-8cbf-66a69ed53c65.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: canode26150331985acr.azurecr.io
          username: ${{ secrets.NODE2_REGISTRY_USERNAME }}
          password: ${{ secrets.NODE2_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: canode26150331985acr.azurecr.io/node2:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NODE2_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n node2 -g haroonfeisal_rg_6674 --server canode26150331985acr.azurecr.io --username  ${{ secrets.NODE2_REGISTRY_USERNAME }} --password ${{ secrets.NODE2_REGISTRY_PASSWORD }}
            az containerapp update -n node2 -g haroonfeisal_rg_6674 --image canode26150331985acr.azurecr.io/node2:${{ github.sha }}
