name: Trigger auto deployment for containerapp node

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/node-AutoDeployTrigger-56a1036e-db3b-4d73-9c90-af3b22a64cb8.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: canodeenv4493305835acr.azurecr.io
          username: ${{ secrets.NODE_REGISTRY_USERNAME }}
          password: ${{ secrets.NODE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: canodeenv4493305835acr.azurecr.io/node:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NODE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n node -g haroonfeisal_rg_6858 --server canodeenv4493305835acr.azurecr.io --username  ${{ secrets.NODE_REGISTRY_USERNAME }} --password ${{ secrets.NODE_REGISTRY_PASSWORD }}
            az containerapp update -n node -g haroonfeisal_rg_6858 --image canodeenv4493305835acr.azurecr.io/node:${{ github.sha }}
